# ---------------------------
# -------- Rosserial --------
# ---------------------------
rosserial_server_dp: 
  ros__parameters:
    port: "/dev/USB0-3" # not used?

# ---------------------------
# ------ Odometry ndoe ------
# ---------------------------
odometry_node:
  ros__parameters:
    # Active this node
    active: true

    # Set publish to this node
    publish: true

    # Open param service
    update_params: false

    # Covariance for "const" part
    covariance_x: 0.001
    covariance_y: 0.001
    covariance_z: 0.001
    covariance_vx: 0.0042
    covariance_vy: 0.0042 
    covariance_vz: 0.005

    # Covariance for "multiple" part
    covariance_multi_vx: 0.
    covariance_multi_vy: 0.
    covariance_multi_vz: 0.

    # Dynamic adjustment from :
      # True: (ns)/cmd_vel
      # False: (ns)/final_pose
    using_nav_vel_cb: false

    # Open if STM has integral information
    use_stm_integral: false

    # Open Dynamic reconfigure service
    using_dynamic_reconf: true

# ----------------------
# ------ IMU node ------
# ----------------------
imu_node:
  ros__parameters:
    # Set the usage of the node
    active: true
    publish: true

    # Open param service
    update_params: false

    # Covariance for "const" part
    covariance_vx: 0.005
    covariance_vy: 0.005
    covariance_vz: 0.001
    covariance_ax: 0.1
    covariance_ay: 0.1
    covariance_az: 0.1

    # Covariance for "multiple" part
    cov_multi_vel: 0.2
    cov_multi_acl: 0.2

    # Use which topic to dynamic adjust covariance
    using_nav_vel_cb: false

    # Low pass filter -> beleive previous
    filter_prev: 0.1

    using_dynamic_reconf: true

# ----------------------
# ------ EKF node ------
# ----------------------
ekf_velocity:
  ros__parameters:
    frequency: 100
    silent_tf_failure: false
    sensor_timeout: 0.01
    two_d_mode: true

    smooth_lagged_data: false
    history_length: 0.4

    dynamic_process_noise_covariance: false

    predict_to_current_time: false

    print_diagnostics: false

    # debug 
    debug: false
    debug_out_file: /path/to/debug/file.txt

    # frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    transform_time_offset: 0.0
    transform_timeout: 0

    # sensors
    # config: [x,   y,   z,
    #          r,   p,   y,
    #          x.,  y.,  z.,
    #          r.,  p.,  y.,
    #          x.., y.., z..]
    odom0: odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true,  true,  false,
                  false, false, true,
                  false, false, false]
    odom0_queue_size: 20
    odom0_differential: false
    odom0_relative: false
    odom0_nodelay: true

    odom0_twist_rejection_threshold: 100

    imu0: imu/data_cov
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false,  false]
    imu0_queue_size: 100
    imu0_differential: false
    imu0_relative: false
    imu0_nodelay: true

    imu0_twist_rejection_threshold: 1000000000000.0
    imu0_linear_acceleration_rejection_threshold: 1000000000000.0

    imu0_remove_gravitational_acceleration: false


    initial_state: [0.0,  0.0,  0.0,
                    0.0,   0.0,   0.0,
                    0.0,   0.0,   0.0,
                    0.0,   0.0,   0.0,
                    0.0,   0.0,   0.0]

    publish_tf: true
    publish_acceleration: true

    # control
    # acc_config: [x., y., z., r., p., y.]
    use_control: false
    stamped_control: false
    control_timeout: 0.2
    control_config: [true, true, false, false, false, true]
    acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.4]
    deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 4.5]
    acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
    deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

    # config:                 [x,     y,     z,    r,    p,    y,     x.,    y.,    z.,   r.,   p.,   y.,   x..,  y..,  z..]
    process_noise_covariance: [1e-6, 0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     1e-6,  0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    1e-6,  0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     1e-2,  0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     1e-2,  0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0.1,  0,    0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    1e-3, 0,    0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    1e-3, 0,
                              0,     0,     0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,    0,    0]
                              
    initial_estimate_covariance: [0.01, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0.01, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0.1,  0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0.01, 0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0.01, 0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0.1,   0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-4, 0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-4, 0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]
