# Obstacle Extractor
# To -> map
obstacle_detector_to_map: 
  ros__parameters:
    active: true
    use_scan: true
    use_pcl: false

    use_split_and_merge: true
    circles_from_visibles: true
    discard_converted_segments: false
    transform_coordinates: true
    
    min_group_points: 5

    max_group_distance: 0.04
    distance_proportion: 0.00628
    max_split_distance: 0.02
    max_merge_separation: 0.25
    max_merge_spread: 0.02
    max_circle_radius: 0.2
    radius_enlargement: 0.05

rival_localization:
  ros__parameters:
    robot_name: robot
    frequency: 10.0
    x_max: 3.0
    x_min: 0.0
    y_max: 2.0
    y_min: 0.0
    vel_lpf_gain: 0.9
    locking_rad: 0.3
    lockrad_growing_rate: 0.3
    is_me: 0.3
    cam_weight: 6.0
    obs_weight: 10.0
    side_weight: 2.0
    cam_side_threshold: 0.2
    side_obs_threshold: 0.2
    obs_cam_threshold: 0.2
    crossed_areas:
      - [2.55, 3.0, 0.65, 1.1]
      - [2.4, 2.85, 1.55, 2.0]
      - [2.0, 3.0, 0.0, 0.15]
      - [1.0, 2.0, 0.0, 0.4]
      - [0.0, 1.0, 0.0, 0.15]
      - [0.0, 0.45, 0.65, 1.1]
      - [0.15, 0.6, 1.55, 2.0]
        - [1.05, 1.95, 1.50, 2.0]

    